version: '2'
services:
 postgresdb:
  image: busybox
  volumes:
    - ./ex:/var/lib/postgresql/data

 postgres:
  name: postgres
  image: postgres:lastest
  hostname: postgres
  volumes_from:
    - postgresdb
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=sa
    - POSTGRES_PASSWORD=sa
